[workspace]
default-members = [
    # "nuefi",
    "macros",
    "core",
    # "self-tests",
    # "test-runner",
]
members = [
    # "nuefi",
    "macros",
    "core",
    "self-tests",
    "test-runner",
]
resolver = "2"

[patch.crates-io]
nuuid = { path = '../Nuuid' }
