[package]
name = "nuefi_core"
version = "0.1.0"
edition = "2021"

[dependencies]
nuuid = { version = "0.5.0", default-features = false }
crc = "3.0.1"
nuefi_macros = { path = "../macros" }
bitflags = "2.3.3"
