[package]
name = "nuefi_core"
version = "0.1.0"
edition = "2021"

[dependencies]
nuuid = { version = "0.4.6", default-features = false }
crc = "3.0.1"
nuefi_macros = { path = "../macros" }
bitflags = "1.3.2"
