export RUSTFLAGS := "\
--cfg special_test\
"

try := ""

@_default:

@test *args='':
    # cargo +nightly nextest run {{args}}
    if [ "{{try}}" == "o" ]; then \
        TRYBUILD="overwrite" cargo test {{args}}; \
    else \
        cargo test {{args}}; \
    fi

@doc *args='':
    cargo +nightly doc --no-deps {{args}}
