export RUSTFLAGS := "\
--cfg special_test\
"

try := ""

@test *args='':
    # cargo +nightly nextest run {{args}}
    if [ "{{try}}" == "o" ]; then \
        TRYBUILD="overwrite" cargo test {{args}}; \
    else \
        cargo test {{args}}; \
    fi

@_default:
